node_name                'nynhex'
client_key               '/Users/nynhex/Dropbox/test_server/.chef/nynhex.pem'
validation_client_name   'chef-validator'
validation_key           '/etc/chef-server/chef-validator.pem'
chef_server_url          'https://localhost'
syntax_check_cache_path  '/Users/nynhex/Dropbox/test_server/.chef/syntax_check_cache'
